In [1]:
import torch

### Tensor Instantiation

In [21]:
# Uninitialized tensor...uses whatever values are left in memory locations
torch.empty(6,2)

tensor([[1.5292e+27, 4.5696e-41],
        [1.5292e+27, 4.5696e-41],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00],
        [7.7052e+31, 7.2148e+22]])

In [14]:
# Initialize with random variables
torch.rand(3,5)

tensor([[0.7156, 0.4958, 0.8036, 0.5361, 0.3697],
        [0.3124, 0.1442, 0.9732, 0.1579, 0.0777],
        [0.3164, 0.6518, 0.6804, 0.6257, 0.9175]])

In [7]:
# Initialize with zeros
# Control data type
torch.zeros(4,4, dtype=torch.long)

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]])

In [23]:
# Initialize with custom values
torch.tensor([3.21,2.22,1.9])

tensor([3.2100, 2.2200, 1.9000])

In [25]:
# Tensor size
torch.empty(4,6).size()

torch.Size([4, 6])

### Tensor Addition

In [27]:
x = torch.ones(4,4)
y = torch.rand(4,4)

In [28]:
print(x + y)

tensor([[1.9469, 1.0129, 1.9299, 1.0503],
        [1.0762, 1.7449, 1.0511, 1.5884],
        [1.3374, 1.3309, 1.2820, 1.5790],
        [1.4608, 1.7303, 1.4245, 1.2945]])


In [29]:
print(torch.add(x,y))

tensor([[1.9469, 1.0129, 1.9299, 1.0503],
        [1.0762, 1.7449, 1.0511, 1.5884],
        [1.3374, 1.3309, 1.2820, 1.5790],
        [1.4608, 1.7303, 1.4245, 1.2945]])


In [33]:
result = torch.empty(4,4)
print(result)
torch.add(x,y,out=result)
print(result)

tensor([[ 1.5292e+27,  4.5696e-41,  1.5292e+27,  4.5696e-41],
        [ 4.4842e-44,  0.0000e+00,  8.9683e-44,  0.0000e+00],
        [-2.4665e+07,  3.0616e-41,  2.2561e-43,  0.0000e+00],
        [-1.9236e+07,  3.0616e-41,  1.5292e+27,  4.5696e-41]])
tensor([[1.9469, 1.0129, 1.9299, 1.0503],
        [1.0762, 1.7449, 1.0511, 1.5884],
        [1.3374, 1.3309, 1.2820, 1.5790],
        [1.4608, 1.7303, 1.4245, 1.2945]])


In [34]:
# Add in place
y.add_(x)
print(y)

tensor([[1.9469, 1.0129, 1.9299, 1.0503],
        [1.0762, 1.7449, 1.0511, 1.5884],
        [1.3374, 1.3309, 1.2820, 1.5790],
        [1.4608, 1.7303, 1.4245, 1.2945]])


### Other

In [36]:
# Can still use standard Numpy indexing
# Row, Column
y[:,1]

tensor([1.0129, 1.7449, 1.3309, 1.7303])

In [42]:
# View to reshape matrix
a = y.view(16)
b = y.view(-1,8)
print(a.shape)
print(b.shape)

torch.Size([16])
torch.Size([2, 8])


In [43]:
# Item to get value of one element in matrix
y[1,1].item()

1.7449417114257812

In [45]:
# Torch to Numpy array
# Data reference remains the same
y.numpy()

array([[1.9469447, 1.012898 , 1.9298873, 1.0502952],
       [1.0762482, 1.7449417, 1.0511317, 1.5883794],
       [1.33742  , 1.3308802, 1.2820365, 1.5789883],
       [1.4608269, 1.7302942, 1.4245446, 1.2944536]], dtype=float32)

In [48]:
# Numpy to Torch
import numpy as np
z = np.ones(5)
torch.from_numpy(z)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)