In [34]:
import torch

In [47]:
# Matrix manipulation acyclic graph built dynamically

x = torch.tensor([[1.,2.],[3.,4.]], requires_grad=True)
print(x)
y = 5 * x
print(y)
z = y.sum()
print(z)

tensor([[1., 2.],
        [3., 4.]], requires_grad=True)
tensor([[ 5., 10.],
        [15., 20.]], grad_fn=<MulBackward0>)
tensor(50., grad_fn=<SumBackward0>)


In [48]:
# Creation function is tracked for each tensor

print(y.grad_fn)
print(z.grad_fn)

In [49]:
# Calculate gradients by following tensor and function graph

z.backward()

#### Backward needs to be done on a single value or given a vector to convert it into a single value

In [50]:
# Get gradients for tensor parameters
# Gradient is independent of values of x

x.grad

tensor([[5., 5.],
        [5., 5.]])

In [53]:
# Control whether grad function is tracked

a = torch.tensor([[2.,4.],[6.,8.]], requires_grad=True)
print(a.requires_grad)

b = (a ** 2)
print(b.requires_grad)

with torch.no_grad():
    c = (b ** 2)
    print(c.requires_grad)

True
True
False


In [54]:
# Detach - copies the tensor but without grad tracking 

print(x.requires_grad)
y = x.detach()
print(y.requires_grad)
print(x.eq(y).all())

True
False
tensor(True)
