In [3]:
import numpy as np
import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from PIL import Image

In [4]:
# Pad

np_im = np.random.randn(2,2)
im = Image.fromarray(np_im)

t1 = transforms.Pad(1)
np_im_t1 = np.array(t1(im))
print(np_im, np_im.shape, np_im_t1, np_im_t1.shape, sep='\n')

[[-0.62199167 -0.7735974 ]
 [ 0.12255782 -0.75580409]]
(2, 2)
[[ 0.          0.          0.          0.        ]
 [ 0.         -0.6219917  -0.7735974   0.        ]
 [ 0.          0.12255782 -0.75580406  0.        ]
 [ 0.          0.          0.          0.        ]]
(4, 4)


In [12]:
# Random Flip

np_im = np.random.randn(2,2)
im = Image.fromarray(np_im)

print(np_im, end='\n\n')

t2 = transforms.RandomHorizontalFlip()
for i in range(5):
    print(np.array(t2(im)), end='\n\n')

[[-0.74864005 -0.32353535]
 [ 0.81333614 -1.80483462]]

[[-0.32353535 -0.74864006]
 [-1.8048346   0.81333613]]

[[-0.32353535 -0.74864006]
 [-1.8048346   0.81333613]]

[[-0.74864006 -0.32353535]
 [ 0.81333613 -1.8048346 ]]

[[-0.32353535 -0.74864006]
 [-1.8048346   0.81333613]]

[[-0.74864006 -0.32353535]
 [ 0.81333613 -1.8048346 ]]



In [16]:
# Random Crop

np_im = np.random.randn(3,3)
im = Image.fromarray(np_im)
print(np_im, end='\n\n')

t3 = transforms.RandomCrop(1)
for i in range(5):
    print(np.array(t3(im)), end='\n\n')


[[-0.46652568  0.00542622  0.112532  ]
 [ 0.0189407   1.06213285 -0.3374066 ]
 [-0.94623909  0.89980614  1.08762077]]

[[0.112532]]

[[0.00542622]]

[[0.89980614]]

[[-0.46652567]]

[[1.0621328]]

